---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator-sa
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-cluster-role
rules:
  - apiGroups: ["devops.orima.com"]
    resources: ["previewenvironments", "previewenvironments/status"]
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["services", "events"]
    verbs: ["*"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["kopf.dev"]
    resources: ["clusterkopfpeerings", "kopfpeerings"]
    verbs: ["*"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operator-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: operator-cluster-role
subjects:
  - kind: ServiceAccount
    name: operator-sa
    namespace: default

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-operator
  template:
    metadata:
      labels:
        app: custom-operator
    spec:
      serviceAccountName: operator-sa
      containers:
        - name: operator
          image: custom-operator:v5
          imagePullPolicy: Never
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
